[[CUDA_JIT]]
arch = "x86_64"
git-tree-sha1 = "77ea887b54ef0e28d7e1c98c6c1e0af4abfbfc8c"
libc = "glibc"
os = "linux"

    [[CUDA_JIT.download]]
    sha256 = "307f887c9b1f521ab90a7bb859cf9ce5e7230758f22d76f3b13fc4396806863d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.x86_64-linux-gnu.tar.gz"
[[CUDA_JIT]]
arch = "powerpc64le"
git-tree-sha1 = "7caebe581c236d7e97caaf3591533acf708f5252"
libc = "glibc"
os = "linux"

    [[CUDA_JIT.download]]
    sha256 = "62a24f26785fda97bfb0e4d469b122040a0987ae4ad4bbe57182522fcb72ff2b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_JIT]]
arch = "aarch64"
git-tree-sha1 = "b6117aa72651fe0679d78ef10bbbb8863fb996f1"
libc = "glibc"
os = "linux"

    [[CUDA_JIT.download]]
    sha256 = "d08c03e66dcfe3f1c2efd6a9ceb87a9e16c090a7b5e23d535f219d67dcc89588"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.aarch64-linux-gnu.tar.gz"
[[CUDA_JIT]]
arch = "x86_64"
git-tree-sha1 = "ad2d0773f2a308c399dfd611c778f1dd98737cc8"
os = "windows"

    [[CUDA_JIT.download]]
    sha256 = "d8d5265a7d517c87a7b72efe734df66b8b8e9ce2ed8cc1e3945122392ffe324d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.x86_64-w64-mingw32.tar.gz"
