[[CUDA_JIT]]
arch = "x86_64"
git-tree-sha1 = "7cbf003f3f408542be0a1b80b586c7b3a2ce31d0"
libc = "glibc"
os = "linux"

    [[CUDA_JIT.download]]
    sha256 = "73b4b13614f8c01866de7cb26053c832b7c3cf45efb063ff0dc2411744e5f415"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.x86_64-linux-gnu.tar.gz"
[[CUDA_JIT]]
arch = "powerpc64le"
git-tree-sha1 = "8d38e19a40e8bbea6cd01b8f0ad2ffae650ae560"
libc = "glibc"
os = "linux"

    [[CUDA_JIT.download]]
    sha256 = "a11f0b220f6a470e9685643546f649a73ad84cde8519efc69d7bc7cdec989fbe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.powerpc64le-linux-gnu.tar.gz"
[[CUDA_JIT]]
arch = "aarch64"
git-tree-sha1 = "c570a3e32963c15a4ce0c86eac83b5864387a944"
libc = "glibc"
os = "linux"

    [[CUDA_JIT.download]]
    sha256 = "32080d3c2cc323866ee387bc1611afb93e3bfcfd54b32d3ad50a13710d93d784"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.aarch64-linux-gnu.tar.gz"
[[CUDA_JIT]]
arch = "x86_64"
git-tree-sha1 = "22bf15590bddff72af430c36fa11629520d0ba77"
os = "windows"

    [[CUDA_JIT.download]]
    sha256 = "764177b672d2df84075e3557f33c2a59aa68aaa0af0910b952fa81ff5c490f0c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_JIT_jll.jl/releases/download/CUDA_JIT-v12.4.1+0/CUDA_JIT.v12.4.1.x86_64-w64-mingw32.tar.gz"
